// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiKBNvDBlILj5UKtoyEPgZ9V2RJ4UfhN4',
    appId: '1:1030863767082:web:af51d32805ef1c2741a553',
    messagingSenderId: '1030863767082',
    projectId: 'chay-luy-72958',
    authDomain: 'chay-luy-72958.firebaseapp.com',
    storageBucket: 'chay-luy-72958.appspot.com',
    measurementId: 'G-HYM5FT96Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5jMBwpiz5pbnTS9vynhwS10uivuS2zRM',
    appId: '1:1030863767082:android:16fa55600eda38d241a553',
    messagingSenderId: '1030863767082',
    projectId: 'chay-luy-72958',
    storageBucket: 'chay-luy-72958.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaT5wZ5QFTf2_rPHDimucSYrf98FfGOBI',
    appId: '1:1030863767082:ios:f7831dcd4ea05ae441a553',
    messagingSenderId: '1030863767082',
    projectId: 'chay-luy-72958',
    storageBucket: 'chay-luy-72958.appspot.com',
    iosBundleId: 'com.example.chayLuy',
  );
}
